### ISSUE TITLE
Decision on editorializing

### ISSUE THREAD

**Issue by tunnell** [hsf-training/pyhep_python_libraries#6]
What's the plan?  Do we just want a brain dump that is welcoming?  Or do we want to curate this a bit?  If we go later, it'll be more useful to new comers, but then we have to make editorial judgements on people's contributions more.  And maybe rank software packages to some extent.

**Comment by eduardo-rodrigues** [comment]
IMO we need to curate, to make the resources as useful as possible. Yes, that will imply editorial judgements. I still have it on my to-do list to read everything carefully and see if there are structure changes needed at this stage ...

**Comment by tunnell** [comment]
OK, agree
